### PR TITLE
Update eclipse-ecsp.jsonnet

### PR DESCRIPTION
**Pull request by AakankshaTejwani**

### CODE REVIEW

**Review by RajendranHarman — APPROVED** [review]

**Comment by netomi** [comment]
fyi: if a project lead approves your PRs you can merge yourself afterwards by adding `/otterdog merge` as a comment (instructions will be added as a comment).

Looking at your project at https://projects.eclipse.org/projects/automotive.ecsp/who and the current project lead team at https://github.com/orgs/eclipse-ecsp/teams/automotive-ecsp-project-leads I see that no project lead is yet invited to this organization. Please check with them to ensure they have added their GitHub handle to their eclipse profile so that they can get invited.

**Review by netomi — APPROVED** [review]
I will approve this PR for now as you dont have any PL yet on GitHub.

**Pull request merged**
